



#define KPLIB_HUD_IDD_UNDEFINED      -1

#define KPLIB_HUD_IDD_RSCTITLE      90000

#define KPLIB_IDD_HUD_OVERLAY           (KPLIB_HUD_IDD_RSCTITLE + 1)

// TODO: TBD: this may or may not work...
#define KPLIB_HUD_IDD_RSCTITLE_BLANK (KPLIB_HUD_IDD_RSCTITLE+1)



#define KPLIB_IDD_HUD_OVERLAY_SITREP_FOB  (KPLIB_HUD_IDD_RSCTITLE+100)

#define KPLIB_IDD_HUD_OVERLAY_SITREP_SECTOR  (KPLIB_HUD_IDD_RSCTITLE+200)


#define KPLIB_IDD_CORE_RSCTITLE_SITREP_HALO (KPLIB_HUD_IDD_RSCTITLE+300)
